package org.avp.client.model.tile.rackmodules;

import com.arisux.mdx.lib.client.Model;

import net.minecraft.client.model.ModelRenderer;

public class ModelRackModule1 extends Model
{
    public ModelRenderer tapeL;
    public ModelRenderer base;
    public ModelRenderer rTape;
    public ModelRenderer light1;
    public ModelRenderer roller;
    public ModelRenderer light2;
    public ModelRenderer light3;
    public ModelRenderer light4;
    public ModelRenderer light5;
    public ModelRenderer light6;
    public ModelRenderer light7;
    public ModelRenderer light8;
    public ModelRenderer lTape;
    public ModelRenderer rTape_1;
    public ModelRenderer lCanisterF;
    public ModelRenderer lLTape;
    public ModelRenderer rLTape;
    public ModelRenderer bLTape;
    public ModelRenderer tLTape;
    public ModelRenderer lLTape2;
    public ModelRenderer rLTape2;
    public ModelRenderer bLTape2;
    public ModelRenderer tLTape2;
    public ModelRenderer lCanisterB;
    public ModelRenderer rCanisterF;
    public ModelRenderer lRTape2;
    public ModelRenderer rRTape2;
    public ModelRenderer bRTape;
    public ModelRenderer tRTape;
    public ModelRenderer lRTape2_1;
    public ModelRenderer rRTape2_1;
    public ModelRenderer bRTape2;
    public ModelRenderer tRTape2;
    public ModelRenderer rCanisterB;

    public ModelRackModule1()
    {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.light2 = new ModelRenderer(this, 0, 15);
        this.light2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light2.addBox(0.5F, 1.0F, -0.5F, 1, 1, 1, 0.0F);
        this.light7 = new ModelRenderer(this, 0, 15);
        this.light7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light7.addBox(-1.5F, 5.5F, -0.5F, 1, 1, 1, 0.0F);
        this.base = new ModelRenderer(this, 0, 18);
        this.base.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.base.addBox(-12.5F, 0.0F, 0.0F, 25, 12, 10, 0.0F);
        this.lLTape = new ModelRenderer(this, 31, 8);
        this.lLTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lLTape.addBox(-3.6F, -2.5F, 0.0F, 1, 5, 1, 0.0F);
        this.light4 = new ModelRenderer(this, 0, 15);
        this.light4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light4.addBox(0.5F, 2.5F, -0.5F, 1, 1, 1, 0.0F);
        this.tLTape = new ModelRenderer(this, 47, 10);
        this.tLTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.tLTape.addBox(-2.5F, -3.5F, 0.0F, 5, 1, 1, 0.0F);
        this.light1 = new ModelRenderer(this, 0, 15);
        this.light1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light1.addBox(-1.5F, 1.0F, -0.5F, 1, 1, 1, 0.0F);
        this.tLTape2 = new ModelRenderer(this, 47, 10);
        this.tLTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.tLTape2.addBox(-2.0F, -4.0F, 0.0F, 4, 1, 1, 0.0F);
        this.lCanisterB = new ModelRenderer(this, 46, 0);
        this.lCanisterB.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lCanisterB.addBox(-4.5F, -4.9F, 1.11F, 9, 9, 0, 0.0F);
        this.rCanisterF = new ModelRenderer(this, 65, 0);
        this.rCanisterF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rCanisterF.addBox(-4.5F, -4.9F, -0.2F, 9, 9, 0, 0.0F);
        this.lTape = new ModelRenderer(this, 13, 0);
        this.lTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lTape.addBox(-5.2F, 10.3F, -1.2F, 6, 0, 1, 0.0F);
        this.setRotation(lTape, 0.0F, 0.0F, 0.22759093446006054F);
        this.tRTape2 = new ModelRenderer(this, 47, 10);
        this.tRTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.tRTape2.addBox(-2.0F, -4.0F, 0.0F, 4, 1, 1, 0.0F);
        this.rTape = new ModelRenderer(this, 31, 0);
        this.rTape.setRotationPoint(7.0F, 5.5F, -1.2F);
        this.rTape.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 1, 0.0F);
        this.tRTape = new ModelRenderer(this, 47, 10);
        this.tRTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.tRTape.addBox(-2.5F, -3.5F, 0.0F, 5, 1, 1, 0.0F);
        this.rCanisterB = new ModelRenderer(this, 65, 0);
        this.rCanisterB.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rCanisterB.addBox(-4.5F, -4.9F, 1.11F, 9, 9, 0, 0.0F);
        this.rLTape2 = new ModelRenderer(this, 36, 9);
        this.rLTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rLTape2.addBox(3.2F, -2.0F, 0.0F, 1, 4, 1, 0.0F);
        this.bRTape = new ModelRenderer(this, 47, 13);
        this.bRTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.bRTape.addBox(-2.5F, 2.5F, 0.0F, 5, 1, 1, 0.0F);
        this.tapeL = new ModelRenderer(this, 31, 0);
        this.tapeL.setRotationPoint(-7.0F, 5.5F, -1.2F);
        this.tapeL.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 1, 0.0F);
        this.bLTape2 = new ModelRenderer(this, 47, 13);
        this.bLTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.bLTape2.addBox(-2.0F, 3.0F, 0.0F, 4, 1, 1, 0.0F);
        this.light3 = new ModelRenderer(this, 0, 15);
        this.light3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light3.addBox(-1.5F, 2.5F, -0.5F, 1, 1, 1, 0.0F);
        this.rLTape = new ModelRenderer(this, 36, 8);
        this.rLTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rLTape.addBox(2.6F, -2.5F, 0.0F, 1, 5, 1, 0.0F);
        this.lLTape2 = new ModelRenderer(this, 31, 9);
        this.lLTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lLTape2.addBox(-4.2F, -2.0F, 0.0F, 1, 4, 1, 0.0F);
        this.lCanisterF = new ModelRenderer(this, 46, 0);
        this.lCanisterF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lCanisterF.addBox(-4.5F, -4.9F, -0.2F, 9, 9, 0, 0.0F);
        this.bLTape = new ModelRenderer(this, 47, 13);
        this.bLTape.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.bLTape.addBox(-2.5F, 2.5F, 0.0F, 5, 1, 1, 0.0F);
        this.rRTape2 = new ModelRenderer(this, 36, 8);
        this.rRTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rRTape2.addBox(2.6F, -2.5F, 0.0F, 1, 5, 1, 0.0F);
        this.rRTape2_1 = new ModelRenderer(this, 36, 9);
        this.rRTape2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rRTape2_1.addBox(3.2F, -2.0F, 0.0F, 1, 4, 1, 0.0F);
        this.bRTape2 = new ModelRenderer(this, 47, 13);
        this.bRTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.bRTape2.addBox(-2.0F, 3.0F, 0.0F, 4, 1, 1, 0.0F);
        this.rTape_1 = new ModelRenderer(this, 13, 0);
        this.rTape_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rTape_1.addBox(-1.0F, 10.3F, -1.2F, 6, 0, 1, 0.0F);
        this.setRotation(rTape_1, 0.0F, 0.0F, -0.22759093446006054F);
        this.light5 = new ModelRenderer(this, 0, 15);
        this.light5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light5.addBox(-1.5F, 4.0F, -0.5F, 1, 1, 1, 0.0F);
        this.lRTape2 = new ModelRenderer(this, 31, 8);
        this.lRTape2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lRTape2.addBox(-3.6F, -2.5F, 0.0F, 1, 5, 1, 0.0F);
        this.roller = new ModelRenderer(this, 0, 0);
        this.roller.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.roller.addBox(-1.5F, 7.6F, -1.2F, 3, 4, 2, 0.0F);
        this.light6 = new ModelRenderer(this, 0, 15);
        this.light6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light6.addBox(0.5F, 4.0F, -0.5F, 1, 1, 1, 0.0F);
        this.lRTape2_1 = new ModelRenderer(this, 31, 9);
        this.lRTape2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.lRTape2_1.addBox(-4.2F, -2.0F, 0.0F, 1, 4, 1, 0.0F);
        this.light8 = new ModelRenderer(this, 0, 15);
        this.light8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.light8.addBox(0.5F, 5.5F, -0.5F, 1, 1, 1, 0.0F);
        this.tapeL.addChild(this.lLTape);
        this.tapeL.addChild(this.tLTape);
        this.tapeL.addChild(this.tLTape2);
        this.tapeL.addChild(this.lCanisterB);
        this.rTape.addChild(this.rCanisterF);
        this.rTape.addChild(this.tRTape2);
        this.rTape.addChild(this.tRTape);
        this.rTape.addChild(this.rCanisterB);
        this.tapeL.addChild(this.rLTape2);
        this.rTape.addChild(this.bRTape);
        this.tapeL.addChild(this.bLTape2);
        this.tapeL.addChild(this.rLTape);
        this.tapeL.addChild(this.lLTape2);
        this.tapeL.addChild(this.lCanisterF);
        this.tapeL.addChild(this.bLTape);
        this.rTape.addChild(this.rRTape2);
        this.rTape.addChild(this.rRTape2_1);
        this.rTape.addChild(this.bRTape2);
        this.rTape.addChild(this.lRTape2);
        this.rTape.addChild(this.lRTape2_1);
    }
    
    @Override
    public void render(Object obj)
    {
        this.light2.render(DEFAULT_SCALE);
        this.light7.render(DEFAULT_SCALE);
        this.base.render(DEFAULT_SCALE);
        this.light4.render(DEFAULT_SCALE);
        this.light1.render(DEFAULT_SCALE);
        this.lTape.render(DEFAULT_SCALE);
        this.rTape.render(DEFAULT_SCALE);
        this.tapeL.render(DEFAULT_SCALE);
        this.light3.render(DEFAULT_SCALE);
        this.rTape_1.render(DEFAULT_SCALE);
        this.light5.render(DEFAULT_SCALE);
        this.roller.render(DEFAULT_SCALE);
        this.light6.render(DEFAULT_SCALE);
        this.light8.render(DEFAULT_SCALE);
    }
}
