package org.avp;

import org.avp.client.Sounds;
import org.avp.entities.living.EntityAethon;
import org.avp.entities.living.EntityAqua;
import org.avp.entities.living.EntityBabyhead;
import org.avp.entities.living.EntityBatXeno;
import org.avp.entities.living.EntityBelugaburster;
import org.avp.entities.living.EntityBelugamorph;
import org.avp.entities.living.EntityBoiler;
import org.avp.entities.living.EntityChestburster;
import org.avp.entities.living.EntityCombatSynthetic;
import org.avp.entities.living.EntityCrusher;
import org.avp.entities.living.EntityDeacon;
import org.avp.entities.living.EntityDeaconShark;
import org.avp.entities.living.EntityDracoEgg;
import org.avp.entities.living.EntityDracoburster;
import org.avp.entities.living.EntityDracomorph;
import org.avp.entities.living.EntityDrone;
import org.avp.entities.living.EntityEngineer;
import org.avp.entities.living.EntityFacehugger;
import org.avp.entities.living.EntityGooMutant;
import org.avp.entities.living.EntityHammerpede;
import org.avp.entities.living.EntityMarine;
import org.avp.entities.living.EntityMyceliomorph;
import org.avp.entities.living.EntityOctohugger;
import org.avp.entities.living.EntityOvamorph;
import org.avp.entities.living.EntityPantheramorph;
import org.avp.entities.living.EntityPraetorian;
import org.avp.entities.living.EntityPredalien;
import org.avp.entities.living.EntityPredalienChestburster;
import org.avp.entities.living.EntityPredatorHound;
import org.avp.entities.living.EntityQueen;
import org.avp.entities.living.EntityQueenChestburster;
import org.avp.entities.living.EntityRoyalFacehugger;
import org.avp.entities.living.EntityRunnerChestburster;
import org.avp.entities.living.EntityRunnerDrone;
import org.avp.entities.living.EntityRunnerWarrior;
import org.avp.entities.living.EntityScelemur;
import org.avp.entities.living.EntitySpaceJockey;
import org.avp.entities.living.EntitySpitter;
import org.avp.entities.living.EntityTrilobite;
import org.avp.entities.living.EntityUltramorph;
import org.avp.entities.living.EntityUrsuidae;
import org.avp.entities.living.EntityWarrior;
import org.avp.entities.living.EntityYautja;
import org.avp.entities.living.EntityYautjaBerserker;
import org.avp.entities.living.EntityYautjaMutant;
import org.avp.item.ItemAPC;
import org.avp.item.ItemArmorMK50;
import org.avp.item.ItemArmorMarine;
import org.avp.item.ItemArmorPressureSuit;
import org.avp.item.ItemArmorTitanium;
import org.avp.item.ItemArmorXeno;
import org.avp.item.ItemDisc;
import org.avp.item.ItemEntitySummoner;
import org.avp.item.ItemFirearm;
import org.avp.item.ItemFirearm.Classification;
import org.avp.item.ItemFirearm.FirearmProfile;
import org.avp.item.ItemFirearm.ItemAmmunition;
import org.avp.item.ItemGrenade;
import org.avp.item.ItemIngotLithium;
import org.avp.item.ItemLaserMine;
import org.avp.item.ItemM240IncineratorUnit;
import org.avp.item.ItemMaintenanceJack;
import org.avp.item.ItemNostromoFlamethrower;
import org.avp.item.ItemPlasmaCannon;
import org.avp.item.ItemShuriken;
import org.avp.item.ItemSpear;
import org.avp.item.ItemStorageDevice;
import org.avp.item.ItemSupplyChute;
import org.avp.item.ItemSupplyChute.SupplyChuteType;
import org.avp.item.ItemWristbracer;

import com.arisux.mdx.MDX;
import com.arisux.mdx.lib.game.Game;
import com.arisux.mdx.lib.game.IPreInitEvent;
import com.arisux.mdx.lib.world.item.HookedItem;
import com.arisux.mdx.lib.world.item.ItemToolMaterialAxe;
import com.arisux.mdx.lib.world.item.ItemToolMaterialPickaxe;

import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBucket;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemSword;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ItemHandler implements IPreInitEvent
{
    public static final ItemHandler instance                 = new ItemHandler();
    public final Summoners          summoners                = new Summoners();

    public Item                     helmXeno                 = (new ItemArmorXeno(AliensVsPredator.materials().armors().chitin, 0, EntityEquipmentSlot.HEAD));
    public Item                     plateXeno                = (new ItemArmorXeno(AliensVsPredator.materials().armors().chitin, 0, EntityEquipmentSlot.CHEST));
    public Item                     legsXeno                 = (new ItemArmorXeno(AliensVsPredator.materials().armors().chitin, 0, EntityEquipmentSlot.LEGS));
    public Item                     bootsXeno                = (new ItemArmorXeno(AliensVsPredator.materials().armors().chitin, 0, EntityEquipmentSlot.FEET));
    public Item                     pressureMask             = new ItemArmorPressureSuit(AliensVsPredator.materials().armors().pressuresuit, 0, EntityEquipmentSlot.HEAD);
    public Item                     pressureChest            = new ItemArmorPressureSuit(AliensVsPredator.materials().armors().pressuresuit, 0, EntityEquipmentSlot.CHEST);
    public Item                     pressurePants            = new ItemArmorPressureSuit(AliensVsPredator.materials().armors().pressuresuit, 0, EntityEquipmentSlot.LEGS);
    public Item                     pressureBoots            = new ItemArmorPressureSuit(AliensVsPredator.materials().armors().pressuresuit, 0, EntityEquipmentSlot.FEET);
    public Item                     mk50helmet               = new ItemArmorMK50(AliensVsPredator.materials().armors().mk50, 0, EntityEquipmentSlot.HEAD);
    public Item                     mk50body                 = new ItemArmorMK50(AliensVsPredator.materials().armors().mk50, 0, EntityEquipmentSlot.CHEST);
    public Item                     mk50pants                = new ItemArmorMK50(AliensVsPredator.materials().armors().mk50, 0, EntityEquipmentSlot.LEGS);
    public Item                     mk50boots                = new ItemArmorMK50(AliensVsPredator.materials().armors().mk50, 0, EntityEquipmentSlot.FEET);
    public Item                     helmMarine               = (new ItemArmorMarine(AliensVsPredator.materials().armors().kevlar, 0, EntityEquipmentSlot.HEAD));
    public Item                     plateMarine              = (new ItemArmorMarine(AliensVsPredator.materials().armors().kevlar, 0, EntityEquipmentSlot.CHEST));
    public Item                     legsMarine               = (new ItemArmorMarine(AliensVsPredator.materials().armors().kevlar, 0, EntityEquipmentSlot.LEGS));
    public Item                     bootsMarine              = (new ItemArmorMarine(AliensVsPredator.materials().armors().kevlar, 0, EntityEquipmentSlot.FEET));
    public Item                     helmTitanium             = (new ItemArmorTitanium(AliensVsPredator.materials().armors().celtic, 0, EntityEquipmentSlot.HEAD));
    public Item                     plateTitanium            = (new ItemArmorTitanium(AliensVsPredator.materials().armors().celtic, 0, EntityEquipmentSlot.CHEST));
    public Item                     legsTitanium             = (new ItemArmorTitanium(AliensVsPredator.materials().armors().celtic, 0, EntityEquipmentSlot.LEGS));
    public Item                     bootsTitanium            = (new ItemArmorTitanium(AliensVsPredator.materials().armors().celtic, 0, EntityEquipmentSlot.FEET));
    public Item                     shovelTitanium           = (new ItemSpade(AliensVsPredator.materials().tools().celtic));
    public Item                     pickaxeTitanium          = (new ItemToolMaterialPickaxe(AliensVsPredator.materials().tools().celtic));
    public Item                     axeTitanium              = (new ItemToolMaterialAxe(AliensVsPredator.materials().tools().celtic));
    public Item                     swordTitanium            = (new ItemSword(AliensVsPredator.materials().tools().celtic));
    public Item                     hoeTitanium              = (new ItemHoe(AliensVsPredator.materials().tools().celtic));
    public Item                     itemSpear                = (new ItemSpear(AliensVsPredator.materials().tools().celtic));
    public Item                     itemWristbracer          = (new ItemWristbracer()).setDescription("Applies " + ItemWristbracer.getDamageToApply() + " damage to any entity, regardless of their armor, while blades are inserted.").setMaxStackSize(1);
    public Item                     itemWristbracerBlades    = (new HookedItem()).setDescription("Place in your wristbracer to equip.").setMaxStackSize(1).setMaxDamage(AliensVsPredator.materials().tools().celtic.getMaxUses());
    public Item                     itemPlasmaCannon         = (new ItemPlasmaCannon()).setFull3D();
    public Item                     itemProximityMine        = (new ItemLaserMine());
    public Item                     itemDisc                 = (new ItemDisc());
    public Item                     itemShuriken             = (new ItemShuriken());
    public Item                     itemGrenade              = (new ItemGrenade(false));
    public Item                     itemIncendiaryGrenade    = (new ItemGrenade(true));
    public Item                     itemAmmoPistol           = ((HookedItem) (new ItemAmmunition(Classification.PISTOL))).setDescription("A magazine classified for use with pistols.");
    public Item                     itemPistolStock          = (new HookedItem()).setDescription("A Pistol stock for use in assembling pistols.").setMaxStackSize(64);
    public Item                     itemPistolBarrel         = (new HookedItem()).setDescription("A Pistol barrel for use in assembling pistols.").setMaxStackSize(64);
    public Item                     itemPistolAction         = (new HookedItem()).setDescription("A Pistol action for use in assembling pistols.").setMaxStackSize(64);
    public Item                     itemAmmoAR               = ((HookedItem) (new ItemAmmunition(Classification.ASSAULT_RIFLE))).setDescription("A magazine classified for use with assault rifles.");
    public Item                     itemAmmoSMG              = ((HookedItem) (new ItemAmmunition(Classification.SUB_MACHINE_GUN))).setDescription("A magazine classified for use with SMGs.");
    public Item                     itemAmmoSniper           = ((HookedItem) (new ItemAmmunition(Classification.RIFLE))).setDescription("A magazine classified for use with standard rifles.");
    public Item                     itemFuelTank             = (new HookedItem()).setDescription("Pressurized fuel tank.").setMaxStackSize(1).setMaxDamage(64);
    public Item                     itemM240ICU              = (new ItemM240IncineratorUnit(itemFuelTank)).setDescription("M240 Incinerator Unit");
    public Item                     itemNostromoFlamethrower = (new ItemNostromoFlamethrower(itemFuelTank)).setDescription("Flame Thrower (Nostromo)");
    public Item                     itemPistol               = (new ItemFirearm(new FirearmProfile(Classification.PISTOL).setAmmoMax(12).setRecoil(2.0F).setRoundsPerMinute(80).setReloadTime(120).setSound(Sounds.SOUND_WEAPON_GUNSHOT)));
    public Item                     itemM4                   = (new ItemFirearm(new FirearmProfile(Classification.ASSAULT_RIFLE).setAmmoMax(24).setRecoil(0.5F).setRoundsPerMinute(800).setReloadTime(120).setSound(Sounds.SOUND_WEAPON_GUNSHOT).setSoundLength(0.75D))).setFull3D();
    public Item                     itemM4Stock              = (new HookedItem()).setDescription("An M4 stock for use in assembling M4s.").setMaxStackSize(64);
    public Item                     itemM4Barrel             = (new HookedItem()).setDescription("An M4 barrel for use in assembling M4s.").setMaxStackSize(64);
    public Item                     itemM4Action             = (new HookedItem()).setDescription("An M4 action for use in assembling M4s.").setMaxStackSize(64);
    public Item                     itemSniper               = (new ItemFirearm(new FirearmProfile(Classification.RIFLE).setAmmoMax(6).setRecoil(1.5F).setRoundsPerMinute(30).setReloadTime(150).setSound(Sounds.SOUND_WEAPON_SNIPER))).setFull3D();
    public Item                     itemSniperStock          = (new HookedItem()).setDescription("A Sniper Rifle stock for use in assembling Sniper Rifles.").setMaxStackSize(64);
    public Item                     itemSniperBarrel         = (new HookedItem()).setDescription("A Sniper Rifle barrel for use in assembling Sniper Rifles.").setMaxStackSize(64);
    public Item                     itemSniperAction         = (new HookedItem()).setDescription("A Sniper Rifle action for use in assembling Sniper Rifles.").setMaxStackSize(64);
    public Item                     itemSniperScope          = (new HookedItem()).setDescription("A Sniper Rifle scope for use in assembling Sniper Rifles.").setMaxStackSize(64);
    public Item                     itemSniperPeripherals    = (new HookedItem()).setDescription("Sniper Rifle peripherals for use in assembling Sniper Rifles.").setMaxStackSize(64);
    public Item                     itemM41A                 = (new ItemFirearm(new FirearmProfile(Classification.ASSAULT_RIFLE).setAmmoMax(99).setRecoil(0.5F).setRoundsPerMinute(900).setReloadTime(120).setSound(Sounds.SOUND_WEAPON_PULSERIFLE).setSoundLength(1.25D))).setFull3D();
    public Item                     itemM41AStock            = (new HookedItem()).setDescription("An M41A stock for use in assembling M41As.").setMaxStackSize(64);
    public Item                     itemM41ABarrel           = (new HookedItem()).setDescription("An M41A barrel for use in assembling M41As.").setMaxStackSize(64);
    public Item                     itemM41AAction           = (new HookedItem()).setDescription("An M41A action for use in assembling M41As.").setMaxStackSize(64);
    public Item                     itemM41APeripherals      = (new HookedItem()).setDescription("M41A peripherals for use in assembling M41As.").setMaxStackSize(64);
    public Item                     itemM56SG                = (new ItemFirearm(new FirearmProfile(Classification.LIGHT_MACHINE_GUN).setAmmoMax(500).setRecoil(0.2F).setRoundsPerMinute(1200).setReloadTime(120).setSound(Sounds.SOUND_WEAPON_M56SG))).setFull3D();
    public Item                     itemM56SGStock           = (new HookedItem()).setDescription("An M56SG stock for use in assembling M56SGs.").setMaxStackSize(64);
    public Item                     itemM56SGBarrel          = (new HookedItem()).setDescription("An M56SG barrel for use in assembling M56SGs.").setMaxStackSize(64);
    public Item                     itemM56SGAction          = (new HookedItem()).setDescription("An M56SG action for use in assembling M56SGs.").setMaxStackSize(64);
    public Item                     itemM56SGSupportFrame    = (new HookedItem()).setDescription("An M56SG support frame for use in assembling M56SGs.").setMaxStackSize(64);
    public Item                     itemM56SGAimingModule    = (new HookedItem()).setDescription("An M56SG aiming module for use in assembling M56SGs.").setMaxStackSize(64);
    public Item                     itemAK47                 = (new ItemFirearm(new FirearmProfile(Classification.ASSAULT_RIFLE).setAmmoMax(32).setRecoil(0.6F).setRoundsPerMinute(600).setReloadTime(100).setSound(Sounds.SOUND_WEAPON_GUNSHOT))).setFull3D();
    public Item                     itemAK47Stock            = (new HookedItem()).setDescription("An AK47 stock for use in assembling AK-47s").setMaxStackSize(64);
    public Item                     itemAK47Barrel           = (new HookedItem()).setDescription("An AK47 barrel for use in assembling AK-47s.").setMaxStackSize(64);
    public Item                     itemAK47Action           = (new HookedItem()).setDescription("An AK47 action for use in assembling AK-47s.").setMaxStackSize(64);
    public Item                     itemDoritos              = (new ItemFood(8, true)).setAlwaysEdible();
    public Item                     itemDoritosCoolRanch     = (new ItemFood(8, true)).setAlwaysEdible();
    public Item                     itemCapacitor            = (new HookedItem()).setDescription("An electrical component used to store energy temporarily.").setMaxStackSize(64);
    public Item                     itemTransistor           = (new HookedItem()).setDescription("A semiconductor used to amplify or switch signals and power.").setMaxStackSize(64);
    public Item                     itemRAM                  = (new HookedItem()).setMaxStackSize(64);
    public Item                     itemResistor             = (new HookedItem()).setDescription("An electrical component that reduces current flow.").setMaxStackSize(64);
    public Item                     itemArtifactTech         = (new HookedItem()).setDescription("An unknown piece of technology acquired from the Yautja species.").setMaxStackSize(64);
    public Item                     itemProcessor            = (new HookedItem()).setDescription("CPU");
    public Item                     itemSolidStateDrive      = (new HookedItem());
    public Item                     itemDiode                = (new HookedItem()).setDescription("An electrical component that conducts in one direction.").setMaxStackSize(64);
    public Item                     itemMotherboard          = (new HookedItem());
    public Item                     itemPowerSupply          = (new HookedItem());
    public Item                     itemSupplyChute          = new ItemSupplyChute(SupplyChuteType.UNBRANDED);
    public Item                     itemSupplyChuteMarines   = new ItemSupplyChute(SupplyChuteType.MARINES);
    public Item                     itemSupplyChuteSeegson   = new ItemSupplyChute(SupplyChuteType.SEEGSON);
    public Item                     itemFlashDrive           = (new ItemStorageDevice()).setDescription("Strange Engineer technology, found at snowy elevations.").setMaxStackSize(64);
    public Item                     itemVoltageRegulator     = (new HookedItem()).setDescription("An electrical component that maintains a constant voltage level.").setMaxStackSize(64);
    public Item                     itemLed                  = (new HookedItem()).setMaxStackSize(64);
    public Item                     itemLedDisplay           = (new HookedItem());
    public Item                     itemCarbon               = (new HookedItem()).setDescription("Used in the crafting of several electrical components.").setMaxStackSize(64);
    public Item                     itemIntegratedCircuit    = (new HookedItem());
    public Item                     itemAPC                  = new ItemAPC();
    public Item                     itemSilicon              = new HookedItem().setDescription("A few chunks of silicon, for use with electronics.");
    public Item                     itemIngotAluminum        = new HookedItem().setDescription("An ingot melted down from bauxite ore, for use with guns.");
    public Item                     itemIngotCopper          = new HookedItem().setDescription("An ingot melted down from copper ore, for use with electronics.");
    public Item                     itemIngotLithium         = ((HookedItem) new ItemIngotLithium()).setDescription("An ingot of lithium. Depletes quickly after processing.");
    public Item                     itemMotionTracker        = ((HookedItem) (new HookedItem())).setDescription("Tracks movement by detecting changes in air density.");
    public Item                     itemPolycarbonate        = (new HookedItem()).setDescription("Polycarbonate (A hard plastic used in the crafting of many items/blocks)");
    public Item                     itemRoyalJelly           = (new HookedItem()).setDescription("Royal Jelly (A potent, transformative substance produced by a Xenomorph Queen)").setMaxStackSize(64);
    public Item                     itemBlackGoo             = (new HookedItem()).setDescription("Black Goo (A0-3959X.91 ? 15)");
    public Item                     itemPhial                = (new HookedItem()).setDescription("A mysterious substance fills this phial");
    public Item                     itemPhialEmpty           = (new HookedItem()).setDescription("An empty glass container of unknown origin");
    public Item                     itemMaintenanceJack      = (new ItemMaintenanceJack()).setDescription("Used to manually pry open blast doors.");
    public Item                     blackGooBucket           = (new ItemBucket(AliensVsPredator.blocks().blockBlackGoo));
    public Item                     mistBucket               = (new ItemBucket(AliensVsPredator.blocks().blockMist));

    public static class Summoners
    {
        public ItemEntitySummoner itemSummonerDrone                 = (new ItemEntitySummoner(EntityDrone.class));
        public ItemEntitySummoner itemSummonerAqua                  = (new ItemEntitySummoner(EntityAqua.class));
        public ItemEntitySummoner itemSummonerWarrior               = (new ItemEntitySummoner(EntityWarrior.class));
        public ItemEntitySummoner itemSummonerCrusher               = (new ItemEntitySummoner(EntityCrusher.class));
        public ItemEntitySummoner itemSummonerSpitter               = (new ItemEntitySummoner(EntitySpitter.class));
        public ItemEntitySummoner itemSummonerPraetorian            = (new ItemEntitySummoner(EntityPraetorian.class));
        public ItemEntitySummoner itemSummonerQueen                 = (new ItemEntitySummoner(EntityQueen.class));
        public ItemEntitySummoner itemSummonerChestburster          = (new ItemEntitySummoner(EntityChestburster.class));
        public ItemEntitySummoner itemSummonerFacehugger            = (new ItemEntitySummoner(EntityFacehugger.class));
        public ItemEntitySummoner itemSummonerMarine                = (new ItemEntitySummoner(EntityMarine.class));
        public ItemEntitySummoner itemSummonerOvamorph              = (new ItemEntitySummoner(EntityOvamorph.class));
        public ItemEntitySummoner itemSummonerRoyalFacehugger       = (new ItemEntitySummoner(EntityRoyalFacehugger.class));
        public ItemEntitySummoner itemSummonerYautja                = (new ItemEntitySummoner(EntityYautja.class));
        public ItemEntitySummoner itemSummonerPredalien             = (new ItemEntitySummoner(EntityPredalien.class));
        public ItemEntitySummoner itemSummonerCombatSynthetic       = (new ItemEntitySummoner(EntityCombatSynthetic.class));
        public ItemEntitySummoner itemSummonerProtomorph            = (new ItemEntitySummoner(EntityDeacon.class));
        public ItemEntitySummoner itemSummonerHammerpede            = (new ItemEntitySummoner(EntityHammerpede.class));
        public ItemEntitySummoner itemSummonerTrilobite             = (new ItemEntitySummoner(EntityTrilobite.class));
        public ItemEntitySummoner itemSummonerYautjaBerserker       = (new ItemEntitySummoner(EntityYautjaBerserker.class));
        public ItemEntitySummoner itemSummonerSpaceJockey           = (new ItemEntitySummoner(EntitySpaceJockey.class));
        public ItemEntitySummoner itemSummonerEngineer              = (new ItemEntitySummoner(EntityEngineer.class));
        public ItemEntitySummoner itemSummonerDeaconShark           = (new ItemEntitySummoner(EntityDeaconShark.class));
        public ItemEntitySummoner itemSummonerRunnerDrone           = (new ItemEntitySummoner(EntityRunnerDrone.class));
        public ItemEntitySummoner itemSummonerRunnerWarrior         = (new ItemEntitySummoner(EntityRunnerWarrior.class));
        public ItemEntitySummoner itemSummonerUltramorph            = (new ItemEntitySummoner(EntityUltramorph.class));
        public ItemEntitySummoner itemSummonerGooMutant             = (new ItemEntitySummoner(EntityGooMutant.class));
        public ItemEntitySummoner itemSummonerAethon                = (new ItemEntitySummoner(EntityAethon.class));
        public ItemEntitySummoner itemSummonerOctohugger            = (new ItemEntitySummoner(EntityOctohugger.class));
        public ItemEntitySummoner itemSummonerBelugaburster         = (new ItemEntitySummoner(EntityBelugaburster.class));
        public ItemEntitySummoner itemSummonerBelugamorph           = (new ItemEntitySummoner(EntityBelugamorph.class));
        public ItemEntitySummoner itemSummonerPredalienChestburster = (new ItemEntitySummoner(EntityPredalienChestburster.class));
        public ItemEntitySummoner itemSummonerQueenChestburster     = (new ItemEntitySummoner(EntityQueenChestburster.class));
        public ItemEntitySummoner itemSummonerRunnerChestburster    = (new ItemEntitySummoner(EntityRunnerChestburster.class));

        public ItemEntitySummoner itemSummonerBabyhead              = (new ItemEntitySummoner(EntityBabyhead.class));
        public ItemEntitySummoner itemSummonerBatXeno               = (new ItemEntitySummoner(EntityBatXeno.class));
        public ItemEntitySummoner itemSummonerBoiler                = (new ItemEntitySummoner(EntityBoiler.class));
        public ItemEntitySummoner itemSummonerDracoburster          = (new ItemEntitySummoner(EntityDracoburster.class));
        public ItemEntitySummoner itemSummonerDracoEgg              = (new ItemEntitySummoner(EntityDracoEgg.class));
        public ItemEntitySummoner itemSummonerDracomorph            = (new ItemEntitySummoner(EntityDracomorph.class));
        public ItemEntitySummoner itemSummonerMyceliomorph          = (new ItemEntitySummoner(EntityMyceliomorph.class));
        public ItemEntitySummoner itemSummonerPantheramorph         = (new ItemEntitySummoner(EntityPantheramorph.class));
        public ItemEntitySummoner itemSummonerPredatorHound         = (new ItemEntitySummoner(EntityPredatorHound.class));
        public ItemEntitySummoner itemSummonerUrsuidae              = (new ItemEntitySummoner(EntityUrsuidae.class));
        public ItemEntitySummoner itemSummonerVardaMonkey           = (new ItemEntitySummoner(EntityScelemur.class));
        public ItemEntitySummoner itemSummonerYautjaMutant          = (new ItemEntitySummoner(EntityYautjaMutant.class));
    }

    @Override
    public void pre(FMLPreInitializationEvent event)
    {
        MDX.registerMappingInfo("summon.protomorph", "summon.deacon", AliensVsPredator.ID);
        
        Game.register(AliensVsPredator.ID, "summon.drone", summoners.itemSummonerDrone).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.warrior", summoners.itemSummonerWarrior).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.runner.drone", summoners.itemSummonerRunnerDrone).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.runner.warrior", summoners.itemSummonerRunnerWarrior).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.crusher", summoners.itemSummonerCrusher).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.spitter", summoners.itemSummonerSpitter).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.praetorian", summoners.itemSummonerPraetorian).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.queen", summoners.itemSummonerQueen).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.predalien", summoners.itemSummonerPredalien).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.deacon", summoners.itemSummonerProtomorph).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.deaconshark", summoners.itemSummonerDeaconShark).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.hammerpede", summoners.itemSummonerHammerpede).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.trilobite", summoners.itemSummonerTrilobite).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.engineer", summoners.itemSummonerEngineer).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.spacejockey", summoners.itemSummonerSpaceJockey).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.ovamorph", summoners.itemSummonerOvamorph).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.facehugger", summoners.itemSummonerFacehugger).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.royalfacehugger", summoners.itemSummonerRoyalFacehugger).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.chestburster", summoners.itemSummonerChestburster).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.yautja", summoners.itemSummonerYautja).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.yautja.berserker", summoners.itemSummonerYautjaBerserker).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.marine", summoners.itemSummonerMarine).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.synthetic.combat", summoners.itemSummonerCombatSynthetic).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.aqua", summoners.itemSummonerAqua).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.ultramorph", summoners.itemSummonerUltramorph).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.goomutant", summoners.itemSummonerGooMutant).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.aethon", summoners.itemSummonerAethon).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.octohugger", summoners.itemSummonerOctohugger).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.belugaburster", summoners.itemSummonerBelugaburster).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.belugamorph", summoners.itemSummonerBelugamorph).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.chestburster.predalien", summoners.itemSummonerPredalienChestburster).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.chestburster.queen", summoners.itemSummonerQueenChestburster).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.chestburster.runner", summoners.itemSummonerRunnerChestburster).setCreativeTab(AliensVsPredator.tabEntities());
        Game.register(AliensVsPredator.ID, "summon.babyhead", summoners.itemSummonerBabyhead).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.batxeno", summoners.itemSummonerBatXeno).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.boiler", summoners.itemSummonerBoiler).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.dracoburster", summoners.itemSummonerDracoburster).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.dracoegg", summoners.itemSummonerDracoEgg).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.dracomorph", summoners.itemSummonerDracomorph).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.myceliomorph", summoners.itemSummonerMyceliomorph).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.pantheramorph", summoners.itemSummonerPantheramorph).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.predatorhound", summoners.itemSummonerPredatorHound).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.ursuidae", summoners.itemSummonerUrsuidae).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.vardamonkey", summoners.itemSummonerVardaMonkey).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());
        Game.register(AliensVsPredator.ID, "summon.yautjamutant", summoners.itemSummonerYautjaMutant).setCreativeTab(AliensVsPredator.tabEntitiesIncomplete());

        Game.register(AliensVsPredator.ID, "helm.pressure", pressureMask).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "body.pressure", pressureChest).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "legwear.pressure", pressurePants).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "boots.pressure", pressureBoots).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "helm.mk50", mk50helmet).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "body.mk50", mk50body).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "legwear.mk50", mk50pants).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "boots.mk50", mk50boots).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "helm.tactical", helmMarine).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "body.tactical", plateMarine).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "legwear.tactical", legsMarine).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "boots.tactical", bootsMarine).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "helm.xeno", helmXeno).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "body.xeno", plateXeno).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "legwear.xeno", legsXeno).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "boots.xeno", bootsXeno).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "helm.celtic", helmTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "body.celtic", plateTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "legwear.celtic", legsTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "boots.celtic", bootsTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.m240icu", itemM240ICU).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.flamethrower.nostromo", itemNostromoFlamethrower).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.pistol", itemPistol).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.m4", itemM4).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.sniper", itemSniper).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.m41a", itemM41A).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.m56sg", itemM56SG).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "gun.ak47", itemAK47).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "bucket.blackgoo", blackGooBucket).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "bucket.mist", mistBucket).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "ammo.ar", itemAmmoAR).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "ammo.pistol", itemAmmoPistol).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "ammo.smg", itemAmmoSMG).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "ammo.sniper", itemAmmoSniper).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "ammo.flamethrower", itemFuelTank).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "grenade.m40", itemGrenade).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "grenade.incindiary", itemIncendiaryGrenade).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "wristblade", itemWristbracer).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "plasmacannon", itemPlasmaCannon).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "mine.laser", itemProximityMine).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "smartdisc", itemDisc).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "shuriken", itemShuriken).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.spear", itemSpear).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.shovel", shovelTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.sword", swordTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.hoe", hoeTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.axe", axeTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.celtic.pick", pickaxeTitanium).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "artifact.tech", itemArtifactTech).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "food.doritos", itemDoritos).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "food.doritos.coolranch", itemDoritosCoolRanch).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "device.nbtdrive", itemFlashDrive).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "device.supplychute", itemSupplyChute).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "device.supplychute.marines", itemSupplyChuteMarines).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "device.supplychute.seegson", itemSupplyChuteSeegson).setCreativeTab(AliensVsPredator.tabMain());

        Game.register(AliensVsPredator.ID, "part.pistol.stock", itemPistolStock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.pistol.barrel", itemPistolBarrel).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.pistol.action", itemPistolAction).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.sniper.stock", itemSniperStock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.sniper.barrel", itemSniperBarrel).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.sniper.action", itemSniperAction).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.sniper.scope", itemSniperScope).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.sniper.peripherals", itemSniperPeripherals).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m41a.stock", itemM41AStock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m41a.action", itemM41AAction).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m41a.barrel", itemM41ABarrel).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m41a.peripherals", itemM41APeripherals).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m56sg.stock", itemM56SGStock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m56sg.action", itemM56SGAction).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m56sg.barrel", itemM56SGBarrel).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m56sg.supportframe", itemM56SGSupportFrame).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m56sg.aimingmodule", itemM56SGAimingModule).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m4.stock", itemM4Stock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m4.action", itemM4Action).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.m4.barrel", itemM4Barrel).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.ak47.action", itemAK47Action).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.ak47.stock", itemAK47Stock).setCreativeTab(AliensVsPredator.tabGunComponents());
        Game.register(AliensVsPredator.ID, "part.ak47.barrel", itemAK47Barrel).setCreativeTab(AliensVsPredator.tabGunComponents());

        Game.register(AliensVsPredator.ID, "part.processor", itemProcessor).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.solidstatedrive", itemSolidStateDrive).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.regulator", itemVoltageRegulator).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.capacitor", itemCapacitor).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.transistor", itemTransistor).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.motherboard", itemMotherboard).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.ram", itemRAM).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.resistor", itemResistor).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.led", itemLed).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.diode", itemDiode).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.ic", itemIntegratedCircuit).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.powersupply", itemPowerSupply).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "part.led.display", itemLedDisplay).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "ingot.copper", itemIngotCopper).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "ingot.lithium", itemIngotLithium).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "ingot.aluminum", itemIngotAluminum).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "silicon", itemSilicon).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "carbon", itemCarbon).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "apc", itemAPC).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "motiontracker", itemMotionTracker).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "wristbracer.blades", itemWristbracerBlades).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "polycarbonate", itemPolycarbonate).setCreativeTab(AliensVsPredator.tabRecipeItems());
        Game.register(AliensVsPredator.ID, "royaljelly", itemRoyalJelly).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "blackgoo.item", itemBlackGoo).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "phial.goo", itemPhial).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "phial.empty", itemPhialEmpty).setCreativeTab(AliensVsPredator.tabMain());
        Game.register(AliensVsPredator.ID, "tool.maintenancejack", itemMaintenanceJack).setCreativeTab(AliensVsPredator.tabMain());
    }
}
