package org.avp.world.dimension.acheron.worldgen.formations;

import java.util.ArrayList;
import java.util.List;

import com.asx.mdx.lib.world.Pos;

public class LV426Formation2 extends LV426Formation
{
    public LV426Formation2()
    {
        ;
    }
    
    @Override
    public Pos[] getOffsets()
    {
        List<Pos> set = new ArrayList<Pos>();
        
        offset(set, 0, 8, 3);
        offset(set, 0, 9, 3);
        offset(set, 0, 10, 3);
        offset(set, 1, 0, 3);
        offset(set, 1, 7, 3);
        offset(set, 1, 8, 1);
        offset(set, 1, 8, 2);
        offset(set, 1, 8, 3);
        offset(set, 1, 8, 4);
        offset(set, 1, 8, 5);
        offset(set, 1, 9, 1);
        offset(set, 1, 9, 2);
        offset(set, 1, 9, 3);
        offset(set, 1, 9, 4);
        offset(set, 1, 9, 5);
        offset(set, 1, 10, 2);
        offset(set, 1, 10, 3);
        offset(set, 1, 10, 4);
        offset(set, 1, 11, 3);
        offset(set, 2, 0, 2);
        offset(set, 2, 0, 3);
        offset(set, 2, 0, 4);
        offset(set, 2, 1, 3);
        offset(set, 2, 4, 3);
        offset(set, 2, 5, 2);
        offset(set, 2, 5, 3);
        offset(set, 2, 5, 4);
        offset(set, 2, 6, 2);
        offset(set, 2, 6, 3);
        offset(set, 2, 6, 4);
        offset(set, 2, 7, 1);
        offset(set, 2, 7, 2);
        offset(set, 2, 7, 3);
        offset(set, 2, 7, 4);
        offset(set, 2, 7, 5);
        offset(set, 2, 8, 1);
        offset(set, 2, 8, 2);
        offset(set, 2, 8, 3);
        offset(set, 2, 8, 4);
        offset(set, 2, 8, 5);
        offset(set, 2, 9, 2);
        offset(set, 2, 9, 3);
        offset(set, 2, 9, 4);
        offset(set, 2, 10, 2);
        offset(set, 2, 10, 3);
        offset(set, 2, 10, 4);
        offset(set, 2, 11, 3);
        offset(set, 3, 0, 1);
        offset(set, 3, 0, 2);
        offset(set, 3, 0, 3);
        offset(set, 3, 0, 4);
        offset(set, 3, 0, 5);
        offset(set, 3, 1, 2);
        offset(set, 3, 1, 3);
        offset(set, 3, 1, 4);
        offset(set, 3, 2, 3);
        offset(set, 3, 3, 3);
        offset(set, 3, 4, 2);
        offset(set, 3, 4, 3);
        offset(set, 3, 4, 4);
        offset(set, 3, 5, 2);
        offset(set, 3, 5, 3);
        offset(set, 3, 5, 4);
        offset(set, 3, 6, 1);
        offset(set, 3, 6, 2);
        offset(set, 3, 6, 3);
        offset(set, 3, 6, 4);
        offset(set, 3, 6, 5);
        offset(set, 3, 7, 2);
        offset(set, 3, 7, 3);
        offset(set, 3, 7, 4);
        offset(set, 3, 8, 3);
        offset(set, 3, 9, 3);
        offset(set, 3, 10, 3);
        offset(set, 4, 0, 1);
        offset(set, 4, 0, 2);
        offset(set, 4, 0, 3);
        offset(set, 4, 0, 4);
        offset(set, 4, 0, 5);
        offset(set, 4, 1, 1);
        offset(set, 4, 1, 2);
        offset(set, 4, 1, 3);
        offset(set, 4, 1, 4);
        offset(set, 4, 1, 5);
        offset(set, 4, 2, 2);
        offset(set, 4, 2, 3);
        offset(set, 4, 2, 4);
        offset(set, 4, 3, 2);
        offset(set, 4, 3, 3);
        offset(set, 4, 3, 4);
        offset(set, 4, 4, 1);
        offset(set, 4, 4, 2);
        offset(set, 4, 4, 3);
        offset(set, 4, 4, 4);
        offset(set, 4, 4, 5);
        offset(set, 4, 5, 1);
        offset(set, 4, 5, 2);
        offset(set, 4, 5, 3);
        offset(set, 4, 5, 4);
        offset(set, 4, 5, 5);
        offset(set, 4, 6, 2);
        offset(set, 4, 6, 3);
        offset(set, 4, 6, 4);
        offset(set, 4, 7, 3);
        offset(set, 4, 8, 3);
        offset(set, 5, 0, 0);
        offset(set, 5, 0, 1);
        offset(set, 5, 0, 2);
        offset(set, 5, 0, 3);
        offset(set, 5, 0, 4);
        offset(set, 5, 0, 5);
        offset(set, 5, 0, 6);
        offset(set, 5, 1, 1);
        offset(set, 5, 1, 2);
        offset(set, 5, 1, 3);
        offset(set, 5, 1, 4);
        offset(set, 5, 1, 5);
        offset(set, 5, 2, 1);
        offset(set, 5, 2, 2);
        offset(set, 5, 2, 3);
        offset(set, 5, 2, 4);
        offset(set, 5, 2, 5);
        offset(set, 5, 3, 1);
        offset(set, 5, 3, 2);
        offset(set, 5, 3, 3);
        offset(set, 5, 3, 4);
        offset(set, 5, 3, 5);
        offset(set, 5, 4, 2);
        offset(set, 5, 4, 3);
        offset(set, 5, 4, 4);
        offset(set, 5, 5, 2);
        offset(set, 5, 5, 3);
        offset(set, 5, 5, 4);
        offset(set, 5, 6, 3);
        offset(set, 6, 0, 0);
        offset(set, 6, 0, 1);
        offset(set, 6, 0, 2);
        offset(set, 6, 0, 3);
        offset(set, 6, 0, 4);
        offset(set, 6, 0, 5);
        offset(set, 6, 0, 6);
        offset(set, 6, 1, 1);
        offset(set, 6, 1, 2);
        offset(set, 6, 1, 3);
        offset(set, 6, 1, 4);
        offset(set, 6, 1, 5);
        offset(set, 6, 2, 1);
        offset(set, 6, 2, 2);
        offset(set, 6, 2, 3);
        offset(set, 6, 2, 4);
        offset(set, 6, 2, 5);
        offset(set, 6, 3, 2);
        offset(set, 6, 3, 3);
        offset(set, 6, 3, 4);
        offset(set, 6, 4, 3);
        offset(set, 6, 5, 3);
        offset(set, 7, 0, 1);
        offset(set, 7, 0, 2);
        offset(set, 7, 0, 3);
        offset(set, 7, 0, 4);
        offset(set, 7, 0, 5);
        offset(set, 7, 1, 1);
        offset(set, 7, 1, 2);
        offset(set, 7, 1, 3);
        offset(set, 7, 1, 4);
        offset(set, 7, 1, 5);
        offset(set, 7, 2, 2);
        offset(set, 7, 2, 3);
        offset(set, 7, 2, 4);
        offset(set, 7, 3, 3);
        offset(set, 7, 4, 3);
        offset(set, 8, 0, 2);
        offset(set, 8, 0, 3);
        offset(set, 8, 0, 4);
        offset(set, 8, 1, 2);
        offset(set, 8, 1, 3);
        offset(set, 8, 1, 4);
        offset(set, 8, 2, 3);
        offset(set, 9, 0, 2);
        offset(set, 9, 0, 3);
        offset(set, 9, 0, 4);
        offset(set, 9, 1, 3);
        offset(set, 10, 0, 3);

        return set.toArray(new Pos[set.size()]);
    }
}